config/routes.rb
Rails.application.routes.draw do
  # root 'display_bookmarks#show'

  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#demolish'
  post 'extension/login' => 'extension#create' #, :defaults => { :format => 'json'}
  get 'extension/login' => 'extension#new'
  post 'extension/lists' => 'extension#show'
  post 'extension/bookmark' => 'extension#new_bookmark'

  get 'display_bookmarks' => 'display_bookmarks#show'

  # get '/sessions' => 'sessions#show'
  # (why did we have that?)

  resources :users, :except => [:destroy] do
    member do
      get :following, :followers
    end
  end

  resources :lists, :except => [:index] do
    resources :bookmarks
    resources :saved_bookmarks, :only => [:destroy]
  end

  resources :upload, :only =>[:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :saved_bookmarks, dependent: :destroy
  has_many :bookmarks, through: :saved_bookmarks
  belongs_to :creator, class_name: "User"

  validates :creator_id, presence: true
  validates :name, presence: true

  def total_bookmarks
    self.saved_bookmarks.count
  end

  def bookmarks_by_name
    self.bookmarks.sort_by {|bookmark| bookmark.name.downcase}
  end

  def bookmarks_by_age
    self.bookmarks.sort_by {|bookmark| bookmark.created_at}
  end

  def bookmarks_by_length
    self.bookmarks.sort_by {|bookmark| bookmark.url.length}
  end

  def bookmarks_by_popularity
    self.bookmarks.sort_by {|bookmark| SavedBookmark.where(bookmark_id: bookmark.id).count}
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def create
    @user = current_user
    if params[:list][:list_to_dup]
      old_list = List.find(params[:list][:list_to_dup].to_i)
      @list = old_list.dup
      @list.update_attributes(creator_id: @user.id)
      old_list.saved_bookmarks.to_a.each do |saved_bookmark|
        new_saved_bookmark = saved_bookmark.dup
        new_saved_bookmark.update_attributes(list_id: @list.id)
      end
      flash[:notice] = "Successfully added list!"
      redirect_to :back
    else
      @list = @user.lists.new(list_params)
      if @list.save
        flash[:notice] = "List successfully created!"
        redirect_to @user
      else
        flash[:alert] = @list.errors.full_messages.first
        redirect_to :new_list
      end
    end
  end

  def new
    if current_user
      @list = List.new
    else
      flash[:notice] = "You must login to create a new form!"
      redirect_to :back
    end
  end

  def edit
    @list = List.find(params[:id])
    unless current_user == User.find(@list.creator_id)
      flash[:alert] = "You must be logged in to edit this"
      redirect_to :list
    end
  end

  def show
    @list = List.find(params[:id])
    case params[:sort]
    when "name"
      @bookmarks = @list.bookmarks_by_name
    when "age"
      @bookmarks = @list.bookmarks_by_age
    when "length"
      @bookmarks = @list.bookmarks_by_length
    when "popularity"
      @bookmarks = @list.bookmarks_by_popularity
    else
      @bookmarks = @list.bookmarks.reverse
    end
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(list_params)
      flash[:notice] = "List name successfully updated!"
      redirect_to @list
    else
      flash[:alert] = "List failed to save"
      redirect_to @list
    end
  end

  def destroy
    puts params
    @list = List.find(params[:id])
    @list.destroy
    redirect_to current_user
  end

  def list_params
    params.require(:list).permit(:name, :list_to_dup)
  end

end

app/views/lists/edit.html.erb
<div class="container">
  <div class="row page-header">
    <div class="col-lg-9">
      <h2>Update folder contents</h2>
        </div>
      </div>
    </div>


    <div class="container ">
      <div class="col-md-8 edit-folder">
          <%= form_for @list, method: "patch", html: {id: "edit-list"} do |f| %>
            <%= f.text_field :name, placeholder: "#{@list.name}", class: "form-control edit-name" %>
            <%= f.submit "Rename folder", class: "btn btn-default" %>
            <button id="bookmark-button" class="btn btn-default mar-left-25">Add New Bookmark</button>
          <% end %>
      </div>
      <br>

      <div class="edit-list">
          <div class="col-md-2">
            <%= form_for :bookmark, url: list_bookmarks_path(@list), html: {id: "bookmark-form"} do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name, placeholder: "name", class: "form-control" %>
            <%= f.label :url %>
            <%= f.text_field :url, placeholder: "url", class: "form-control" %>
            <br>
            <%= f.submit "Add", class: "btn btn-default" %>
            <% end %>
      </div>
    </div>

    <br>

    <div col="col-md-6" class="mar-left-1">
      <% @list.saved_bookmarks.each do |saved_bookmark| %>
      <table class="bookmark-table">
      <tr>
        <td class="not-so-wide"><%= link_to "Delete", {action: :destroy, list_id: @list.id, saved_bookmark_id: saved_bookmark.id, controller: "saved_bookmarks"}, :method => :delete, class: "mint-green table-delete-btn" %></td>
        <td class="bkmk-name"><%= saved_bookmark.bookmark.name %></td>
      </tr>
    </table>
      <% end %>

  <br>
  <div class="mar-left-50">

  </div>
  </div>

</div>

app/views/lists/new.html.erb
<div class="container " id="padding-top">
	<div class="row">
		<div class="page-header">
			<h2>Create a folder</h2>
			<div class="list-author">
    	<h5><%= link_to "Back to Profile", current_user %></h5>
  	</div>
			</div>
		<div class="col-md-4">

			<div class="form-group">
				<%= form_for @list, html: {class: "form-inline", id: "create-list"} do |f| %>
				  <%= f.text_field :name, placeholder: "Folder name", class: 'form-control' %>
				  <%= f.submit "Create", class: "btn btn-default" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/lists/show.html.erb
<div class="container-cubes ">
  <div class="folder-page-header">

      <h2><%= @list.name.capitalize %></h2>
      <div class="list-author">
        <% if current_user == @list.creator %>
          <h5 class="back"><%= link_to "Back to folder view", current_user %></h5>
        <% else %>
          <h5><%= link_to @list.creator.username, @list.creator %></h5>
        <% end %>
      </div>
  </div>

<div class="dropdown pull-right test-class" role="group">
  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Options
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li class="dropdown-header">Sort folders</li>
    <li><%= link_to "Alphabetically", :action => "show", :sort => "name" %></li>
    <li><%= link_to "By popularity", :action => "show", :sort => "popularity" %></li>
    <li><%= link_to "By default", :action => "show", :sort => "age" %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Edit this folder", :action => "edit" %></li>
  </ul>
</div>

<% if @bookmarks %>

  <p id="bookmark-sort"><% @bookmarks.each do |bookmark| %></p>

  <a href="<%= bookmark.url %>" target="_blank">
  <li class="display">
    <div class="website" onclick="return true">
      <div class="snapshot">
        <h3 class="bookmark-title"><%= truncate(bookmark.name.capitalize, length: 12, separator: ' ') %></h3>

        <div class="snapshot-image">
        <% if bookmark.snapshot %>
          <% if bookmark.snapshot.thumbnail %>
            <%= image_tag bookmark.snapshot.thumbnail.url, class:"thumbnail" %>
          <% end %>
        <% else %>
          <%= image_tag "missing-thumb.jpg", class:"thumbnail" %>
        <% end %>
        </div>
      </div>
      <div class="details">
        <header>
          <h1><%= bookmark.name.capitalize %></h1>
          <span class="site-info"></span>    <!-- placeholder for future text -->
        </header>
        <p>
          Notes about this bookmark will go here.
        </p>
      </div>
    </div>
  </a>
  <% end %>
<% else %>
  <p class="text-warning">Sorry but it doesn't look like you have any bookmarks yet :(</p>
<% end %>