config/routes.rb
Rails.application.routes.draw do
  # root 'display_bookmarks#show'

  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#demolish'
  post 'extension/login' => 'extension#create' #, :defaults => { :format => 'json'}
  get 'extension/login' => 'extension#new'
  post 'extension/lists' => 'extension#show'
  post 'extension/bookmark' => 'extension#new_bookmark'

  get 'display_bookmarks' => 'display_bookmarks#show'

  # get '/sessions' => 'sessions#show'
  # (why did we have that?)

  resources :users, :except => [:destroy] do
    member do
      get :following, :followers
    end
  end

  resources :lists, :except => [:index] do
    resources :bookmarks
    resources :saved_bookmarks, :only => [:destroy]
  end

  resources :upload, :only =>[:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  validates :user_id, presence: true
  validates :client_file, presence: true

  belongs_to :user

  has_attached_file :client_file

end

app/controllers/upload_controller.rb
class UploadController < ApplicationController

  def new
    if current_user
      @upload = Upload.new
    else
      flash[:alert] = "You must be logged in to upload your bookmarks!"
      redirect_to :root
    end
  end

  def create
    if params[:upload]
      @bookmark_html = params[:upload][:upload_file_name].read
      if ParseBookmarks.call(@bookmark_html, current_user) == false
        flash[:alert] = "Invalid or empty file!"
        redirect_to :new_upload
      else
        redirect_to user_path(current_user)
      end
    else
      flash[:alert] = "You need to select a file first!"
      redirect_to :new_upload
    end
  end

  def destroy

  end

private
  def file_upload_params
    params.require(:upload).permit(:upload_file_name, :upload_content_type, :upload_file_size)
  end

end

app/views/upload/new.html.erb
<div class="container">
		
	<div class="page-header"><h1>Upload Chrome Bookmark HTML file</h1>
		<div class="list-author">
    	<h5><%= link_to "Back to Profile", current_user %></h5>
  	</div>
  </div>
  
		<div class="col-md-4">
			<%= form_for @upload, url: upload_index_path, class: "form-inline", multipart: true do |f| %>


				<div class="form-group">
					<%= f.file_field :upload_file_name, class: 'form-control'%>
				</div>

			  <%= f.submit 'Upload', class: 'btn btn-default' %>
			<% end %>
		</div>
	</div>
</div>