config/routes.rb
Rails.application.routes.draw do
  # root 'display_bookmarks#show'

  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#demolish'
  post 'extension/login' => 'extension#create' #, :defaults => { :format => 'json'}
  get 'extension/login' => 'extension#new'
  post 'extension/lists' => 'extension#show'
  post 'extension/bookmark' => 'extension#new_bookmark'

  get 'display_bookmarks' => 'display_bookmarks#show'

  # get '/sessions' => 'sessions#show'
  # (why did we have that?)

  resources :users, :except => [:destroy] do
    member do
      get :following, :followers
    end
  end

  resources :lists, :except => [:index] do
    resources :bookmarks
    resources :saved_bookmarks, :only => [:destroy]
  end

  resources :upload, :only =>[:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Bookmark It!</title>
  <!-- <link href='https://fonts.googleapis.com/css?family=Arimo:400,400italic,700,700italic' rel='stylesheet' type='text/css'> -->
  <link href='https://fonts.googleapis.com/css?family=Candal' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
        <a class="navbar-brand" href="/display_bookmarks">Bookmark It!</a>
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <div class="pull-right">
        <ul class="nav navbar-nav">
          <% if session[:user_id] %>
            <!-- <li><%= link_to "Home", :root %></li> -->
            <li><%= link_to "Profile (#{current_user.username})", User.find(session[:user_id]) %></li>
            <li><%= link_to "Upload", :new_upload %></li>
            <li> <%= link_to "Logout", logout_path, method: "delete" %></li>
          <% else %>
            <!-- <li><%= link_to "Home", :root %></li> -->
            <!-- <li><%= link_to "Register", :new_user %></li> -->
        </ul>
      </div>
            <%= form_for :session, url: login_path, html: {class: "navbar-form navbar-right"} do |f| %>
              <div class="form-group">
                <%= f.text_field :username, placeholder: "username", class: "form-control" %>
                <%= f.password_field :password, placeholder: "password", class: "form-control" %>
              </div>
              <%= f.submit "Login", class: "btn btn-success" %>
              <% if !session[:user_id] %>
                <%= link_to "Register", :new_user %>
              <% end %>
            <% end %>
          <% end %>
      </div>
    </div>
  </nav>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  <% if flash[:alert] %>
      <%= flash[:alert] %>
  <% end %>

<!-- don't remove yield! -->
<div class = "container-fluid">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmark It!</title>
  <%= favicon_link_tag 'favicon.png' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Register Here!</h4>
      </div>
        <div class="modal-body">
          <%= render 'users/new' %>
        </div>

    </div>
  </div>
</div>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

  <!-- Navigation -->
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse"><i class="fa fa-bars"></i></button>
          <a class="navbar-brand page-scroll" href="#page-top">
              <%= link_to "<i class'fa fa-play-circle'></i><div id='logo'><span class='light'>Bookmark</span> It!</div>".html_safe, :root %>
          </a>
      </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
        <!-- <div class="pull-right"> -->
          <ul class="nav navbar-nav">
            <% if session[:user_id] %>
              <li><%= link_to "Explore!", users_path %></li>
              <li><%= link_to "#{current_user.username}", User.find(session[:user_id]) %></li>
              <li><%= link_to "Upload", :new_upload %></li>
              <li> <%= link_to "Logout", logout_path, method: "delete" %></li>

          <% else %>
          <li><%= form_for :session, url: login_path, html: {class: "navbar-form navbar-right"} do |f| %></li>
            <li><%= f.text_field :username, placeholder: "username", class: "form-control" %></li>
            <li><%= f.password_field :password, placeholder: "password", class: "form-control" %></li>
            <li><%= f.submit "Login", class: "btn btn-success" %></li>
            <% end %>

            <% if !session[:user_id] %>
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal">
            Register
            </button>
            <% end %>
            <% end %>

            </ul>
          </div>
      </div>
    </div><!--/. container -->
  </nav>




  <%= yield %>

</body>
</html>

app/views/layouts/display_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookmarkIt</title>
  <%= stylesheet_link_tag    'application', 'custom', 'boxes', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
        <a class="navbar-brand" href="/display_bookmarks">Bookmark It!</a>
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if session[:user_id] %>
            <!-- <li><%= link_to "Home", :root %></li> -->
            <li><%= link_to "Profile (#{current_user.username})", User.find(session[:user_id]) %></li>
            <li> <%= link_to "Logout", logout_path, method: "delete" %></li>
          <% else %>
            <!-- <li><%= link_to "Home", :root %></li> -->
            <!-- <li><%= link_to "Register", :new_user %></li> -->
        </ul>
            <%= form_for :session, url: login_path, html: {class: "navbar-form navbar-right"} do |f| %>
              <div class="form-group">
                <%= f.text_field :username, placeholder: "username", class: "form-control" %>
                <%= f.password_field :password, placeholder: "password", class: "form-control" %>
              </div>
              <%= f.submit "Login", class: "btn btn-success" %>
              <% if !session[:user_id] %>
                <%= link_to "Register", :new_user %>
              <% end %>
            <% end %>
          <% end %>
      </div>
    </div>
  </nav>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  <% if flash[:alert] %>
      <%= flash[:alert] %>
  <% end %>

<!-- don't remove yield! -->
<div class = "container-fluid">
  <%= yield %>
</div>
</body>
</html>